apiVersion: v1
kind: Service
metadata:
  name: basicgamearena-service
spec:
  type: NodePort
  selector:
    app: basicgamearena
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081